### GET ALL
GET http://localhost:3000/alquileres

### POST
# @name createAlquiler
POST http://localhost:3000/alquileres/
Content-Type: application/json

{
"cliente":1,
"empleado": 1,
"vehiculo": 1,
"fechaInicio": "2024-07-28",
"fechaFin": "2024-07-30",
"estado": "Iniciado",
"precio": 20000
}

### ID
@id = {{createAlquiler.response.body.data.id}}

### GET ONE
GET http://localhost:3000/alquileres/{{id}}


### PUT
PUT http://localhost:3000/alquileres/{{id}}
Content-Type: application/json

{
"estado":"iniciadoooooooo"
}

### DELETE
DELETE http://localhost:3000/alquileres/{{id}}