### GET ALL
GET http://localhost:3000/customers

### POST

# @name createCustomer
POST http://localhost:3000/customers/
Content-Type: application/json

{
"dni": 58651,
"firstName": "marcosTEST",
"lastName": "perez",
"email":"andresperez@gmail.com",
"password": "4532",
"address": "Salta 1500",
"phone": "346845326",
"locality": 2
}

### ID
@id = {{createCustomer.response.body.data.id}}

### GET ONE
GET http://localhost:3000/customers/{{id}}

### PUT
PUT http://localhost:3000/customers/{{id}}
Content-Type: application/json

{
"email":"martinadiazzzzz@gmail.com"
}

### DELETE
DELETE http://localhost:3000/customers/{{id}}