### GET ALL
GET http://localhost:3000/rentals

### POST
# @name createRental
POST http://localhost:3000/rentals/
Content-Type: application/json

{
"customer":1,
"employee": 1,
"vehicle": 1,
"startDate": "2024-07-28",
"endDate": "2024-07-30",
"status": "Started",
"price": 20000
}

### ID
@id = {{createRental.response.body.data.id}}

### GET ONE
GET http://localhost:3000/rentals/{{id}}

### PUT
PUT http://localhost:3000/rentals/{{id}}
Content-Type: application/json

{
"status":"starteddddddd"
}

### DELETE
DELETE http://localhost:3000/rentals/{{id}}