### GET ALL
GET http://localhost:3000/empleados

### POST
# @name createEmpleado
POST http://localhost:3000/empleados/
Content-Type: application/json

{
"dni":12345678,
"nombre": "Martina",
"apellido": "Diaz",
"email":"martinadiaz@gmail.com",
"clave": "123456"
}

### ID
@id = {{createEmpleado.response.body.data.id}}

### GET ONE
GET http://localhost:3000/empleados/{{id}}

### PUT
PUT http://localhost:3000/empleados/{{id}}
Content-Type: application/json

{
"email":"martinadiazzzzz@gmail.com"
}

### DELETE
DELETE http://localhost:3000/empleados/{{id}}