### Obtener todos los usuarios
GET http://localhost:3000/api/clientes

### Crear nueva localidad

# @name createCliente
POST http://localhost:3000/api/clientes/
Content-Type: application/json

{
"dni":12345678,
"nombre": "Martina",
"apellido": "Diaz",
"email":"martinadiaz@gmail.com",
"clave": "123456",
"direccion": "Salta 200",
"telefono": "346845326",
"localidad": 1
}

### ID
@id = {{{{createCliente.response.body.data.id}}}}

### Obtener un Usuario
GET http://localhost:3000/api/clientes/1


### Modificar un Usuario (Completamente)
PUT http://localhost:3000/api/clientes/1
Content-Type: application/json

{
"email":"martinadiazzzzz@gmail.com"
}


### Borrar un Usuario
DELETE http://localhost:3000/api/clientes/1