### Obtener todas las localidades
GET http://localhost:3000/api/localidades

### Crear nueva localidad

# @name createLocalidad
POST http://localhost:3000/api/localidades/
Content-Type: application/json

{
"nombre": "Chabas",
"provincia": "Santa Fe"
}

### ID
@id = {{{{createLocalidad.response.body.data.id}}}}

### Obtener una localidad
GET http://localhost:3000/api/localidades/4


### Modificar una localidad (Completamente)
PUT http://localhost:3000/api/localidades/2
Content-Type: application/json

{
"nombre": "Firmat",
"provincia": "Santa Fe"
}


### Borrar una localidad
DELETE http://localhost:3000/api/localidades/4