### GET ALL
GET http://localhost:3000/api/localidades

### POST
# @name createLocalidad
POST http://localhost:3000/api/localidades/
Content-Type: application/json

{
"nombre": "Rosario",
"provincia": "Santa Fe"
}

### ID
@id = {{createLocalidad.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/localidades/{{id}}

### PUT
PUT http://localhost:3000/api/localidades/2
Content-Type: application/json

{
"nombre": "Arias",
"provincia": "Cordoba"
}

### DELETE
DELETE http://localhost:3000/api/localidades/{{id}}