### GET ALL
GET http://localhost:3000/localities

### POST
# @name createLocalidad
POST http://localhost:3000/localities/
Content-Type: application/json

{
"name": "Rosario",
"province": "Santa Fe"
}

### ID
@id = {{createLocalidad.response.body.data.id}}

### GET ONE
GET http://localhost:3000/localidades/{{id}}

### PUT
PUT http://localhost:3000/localidades/{{id}}
Content-Type: application/json

{
"name": "Arias",
"province": "Cordoba"
}


### DELETE
DELETE http://localhost:3000/localidades/{{id}}