### GET ALL
GET http://localhost:3000/localidades

### POST
# @name createLocalidad
POST http://localhost:3000/localidades/
Content-Type: application/json

{
"name": "Arias",
"province": "Cordoba"
}

### ID
@id = {{createLocalidad.response.body.data.id}}

### GET ONE
GET http://localhost:3000/localidades/{{id}}

### PUT
PUT http://localhost:3000/localidades/2
Content-Type: application/json

{
"name": "Arias",
"province": "Cordoba"
}


### DELETE
DELETE http://localhost:3000/localidades/{{id}}