### GET ALL

GET http://localhost:3000/api/vehiculos-tipos

### POST
# @name createTipoVehiculo
POST http://localhost:3000/api/vehiculos-tipos
Content-Type: application/json

{
"tipo": "SUV",
"descripcion": "Tamaño promedio, perfecto para familias"
}

### ID
@id = {{createTipoVehiculo.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/vehiculos-tipos/{{id}}

### PUT
PUT http://localhost:3000/api/vehiculos-tipos/{{id}}
Content-Type: application/json

{
"tipo": "4x4 MODIFICADO",
"descripcion": "Gran tamaño, traccion AWD MODIFICADO"
}

### DELETE
DELETE http://localhost:3000/api/vehiculos-tipos/{{id}}