### GET ALL

GET http://localhost:3000/api/vehiculos-tipos

### POST

POST http://localhost:3000/api/vehiculos-tipos
Content-Type: application/json

{
"tipo": "4x4",
"descripcion": "Gran tamaño, traccion AWD"
}
### GET ONE

GET http://localhost:3000/api/vehiculos-tipos/3

### PUT
PUT http://localhost:3000/api/vehiculos-tipos/3
Content-Type: application/json

{
"tipo": "4x4 MODIFICADO",
"descripcion": "Gran tamaño, traccion AWD MODIFICADO"
}


### DELETE
DELETE http://localhost:3000/api/vehiculos-tipos/3