### GET ALL
GET http://localhost:3000/vehiculos

### POST
# @name createVehiculo
POST http://localhost:3000/vehiculos
Content-Type: application/json

{
"patente": "testPatente",
"marca": "Ford",
"modelo": "Raptor",
"estado": "Disponible",
"tipoVehiculo": 1   
}

### ID
@id = {{createVehiculo.response.body.data.id}}

### GET ONE
GET http://localhost:3000/vehiculos/{{id}}

### PUT
PUT http://localhost:3000/vehiculos/{{id}}
Content-Type: application/json

{
"patente": "testPatente MODIFICADO",
"marca": "Ford",
"modelo": "RaptorCITO",
"tipoVehiculo": 1  
}

### DELETE
DELETE http://localhost:3000/vehiculos/{{id}}